### ISSUE TITLE
nPose Hawthorn Release Candidate demo

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#21]
`DEFAULT:Meditate:Pair`
contains an unnessecary
`LINKMSG|-1812221819|read,MyBaseRLVrestrictions(firstSet)`

`DEFAULT:Meditate:Pair`
contains an unknown global option called:
`menu_order_card=Change Menu Order`

**Comment by HowardBaxton** [comment]
removed both
