### ISSUE TITLE
Reservation of linkMessage# 2731

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#41]
I want to extent the plugin "plugin_lockmeister_lockguard" a little. Therefore I need a new linkMessage#. "plugin_lockmeister_lockguard" currently uses 2732 and 2733.

**Comment by HowardBaxton** [comment]
Please add another 2734.  I would have added this now but I have nothing for the description it would use.  I will leave it for you to add.

**Comment by LeonaMorro** [comment]
2734 added to lm list
