### ISSUE TITLE
SAT_NOTSAT handler problem while adjusting

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#47]
Howard:
I noticed last night there is another anomaly that requires looking into with more importance than the above: When Adjusters are rezzed and selecting the same pose from the menu, SAT and NOTSATMSG's are run (not just once but twice). This doesn't happen when Adjusters are not rezzed (all functions as intended). I have not verified this on older versions but I am certain it will also be seen there. The SAT_NOTSAT handler would need to know if adjusters are in play and not react in this situation and currently there is no means for the 'handler' to get this info.

**Comment by LeonaMorro** [comment]
Why does the slave send a SEAT_UPDATE + 2000000 message AND a SEAT_UPDATE message on an incomming ADJUSTER_REPORT?

**Comment by HowardBaxton** [comment]
Seatupdate is broadcast to everyone but seatupdate+2000.... Only goes to
the core

**Comment by LeonaMorro** [comment]
But wich other script (beside the core) needs to know if the slots list is changed by the Adjuster?

**Comment by HowardBaxton** [comment]
I am not where I can look at the scripts but I think the core must do
assignslots when the adjuster updates.  The normal seatupdate goes out
after that to tell all others of the update.  Everyone else does their
thing on the normal seatupdate.  The +20000... Is only for the core.  Again
this is from my memory which fails me sometime.  I should verify what I say.

**Comment by LeonaMorro** [comment]
Yes, you should verify that, because the SEAT_UPDATE created by the slave while using the adjusters is the cause for running the (NOT)SATMSGs. So the question should be: Do any script needs the new rot/pos information that are generated while using the adjusters (beside the core which get the information via the SEAT_UPDATE + 2000000)?

**Comment by HowardBaxton** [comment]
This problem was cause because the Adjuster did not have the correct initial position.  Branch "A-change-I-can-live-with" addresses the issue in the Adjuster script.

**Comment by LeonaMorro** [comment]
should be fixed with 7af207291bbebce6c9fe0a23e6b8d16af7c73ce9 ?

**Comment by HowardBaxton** [comment]
Yes indeed, that fixes this issue.
