### ISSUE TITLE
Sorting issue in swap seat menu

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#54]
I rencently noticed an unexpected button order in swap seats menu. I have to check it again.

**Comment by HowardBaxton** [comment]
Buttons are put in alphanumeric order in the dialog function now.  This is the probable cause.  Before only the choices list was put into alphanumeric order, now choices are combined with buttons prior to the sort.  In most cases, this would mean BTN and SET cards are sorted together.

If my memory is correct, the sort doesn't happen if .Change Menu Order is used.

I am not sure what the fix will entail.

**Comment by LeonaMorro** [comment]
No no .. I don't mean the sorting of the "normal" Buttons. I mean the button order in the menu where you can change to another seat.

**Comment by LeonaMorro** [comment]
Ok .. I will look there .. tomorrow ;)

**Comment by HowardBaxton** [comment]
if .Change Menu Order notecard is not in contents, the buttons get sorted.  I just checked and that is the problem, the sort can be removed if we cannot find a suitable solution.  That will mean the BTN NC's will come first, and then the DEFAULT, and finally the SET NC's.

**Comment by LeonaMorro** [comment]
fixed with 656e7f158664160bd59d727e93b2457a22212c47
