### ISSUE TITLE
Props issue

### ISSUE THREAD

**Issue by HowardBaxton** [HowardBaxton/nPose#58]
When rezzing one prop as "Normal" and another as "Explicit" within the same notecard, they both take on the properties of the last line in NC.

Tried adding a PAUSE between, putting "Explicit" first with ANIM line and Pause between, added many blank lines between without the PAUSE.  Nothing seems to help.

**Comment by HowardBaxton** [comment]
Seems that ProcessLine function used to be called from the dataserver event where the process would finish after each line was read.  The listener could get a ping from the newly rezzed prop between dataserver events.  

Now ProcessLine function is called from within a loop and the loop must finish before the listener event gets a ping from the prop plugin.  The "Explicit" flag is not current for each prop, but takes on the last PROP line setting.

**Comment by HowardBaxton** [comment]
Here is something that works:
1.  Rez normal props first in the SET NC
2.  Use LINKMSG|207|rezExplicit Within rezExplicit NC add lines to rez the explicit props.  (207 == DOACTION)

Not and elegant solution.

Possibility 1:
1.  Add explicit flag to a list in the order they are done in ProcessLine function
2.  Rely on object_rez event to happen before the listen event.
3.  Rely on object_rez event to get the keys in the order they are rezzed and add the key to this list.
4.  When pings come in, grab the corresponding explicit flag and send it back to that specific prop.

Managing the list becomes a problem.

Possibility 2:
1.  Require unique names for every prop and grab the unique name and flag for a strided list.
2.  When pings come in, match up name with explicit flag from the list and send back to that specific prop.

Also managing the list becomes a problem

Possibility 3:
1.  NC Reader send a begin flag and EOF flag.
2.  NC Reader sends one line at a time for processing.
This can break the loop and allow the listen event to receive the ping from newly rezzed prop.  The listen event can then grab the most recent explicit flag to send out to this prop.
3.  Use the EOF flag to fire assignSlots and also in the listen event to clear the list.

None of these possibilities are elegant.  I am out of ideas for now.  This will require more thought.

**Comment by HowardBaxton** [comment]
Possibility 4:
Make two props plugins, one for normal props and another for explicit props.

Also not elegant

**Comment by LeonaMorro** [comment]
I guess the main problem is (again) that the Prop (adjuster) get the needed informations not during the rezz (rezParam) but tries to fetch the params via a regionSay ping.

Possibility 5:
Rezz the prop with the needed parameter

**Comment by HowardBaxton** [comment]
I am not in favor of Possibility 5 due to the huge scope.  It will not only break Adjuster and Prop plugin, it will break many plugins we don't even know exist.

If I remember correctly, the scope of this change even has an affect on other basic scripts.  (Maybe I'm wrong on this.)

**Comment by LeonaMorro** [comment]
I mentioned the adjuster only because it was (is) a similar problem. The Props don't use a start param currently (as far as I see)

**Comment by HowardBaxton** [comment]
llRezAtRoot(obj, llGetPos(), ZERO_VECTOR, rot, chatchannel);

Same problem as Adjusters, we send chatchannel.

**Comment by LeonaMorro** [comment]
Ok.. I see .you are totaly right.

Possibility 1:
the time between to rezzing commands could be very short: I don't expect that the on_rez events or the listen events would be in the right order
Possibility 2:
can a single prop be rezzed twice currently?
Possibility 3:
this is a worse idea. It will flood the object with linkmessages.
Possibility 4:
Could work
Possibility 5:
Could work

**Comment by HowardBaxton** [comment]
I agree with all your comments.  I am not in favor of any of these possibilities.
Possibility 5 would be perfect in a V2 but it's scope is very dangerous in current nPose.

The branch I made does work and if lag doesn't change drastically within the process, all props should be subject to the same lag.  That branch is most promising so far even if it could break on minimum of situations.  It is elegant in that the ping response talks directly to one prop rather than broadcasting.

Without a more elegant solution, I am in favor of the approach in the branch.  Maybe give it a day of pondering before a commit.

**Comment by LeonaMorro** [comment]
As far as I see the the changes you made are the Possibility 1? ... If yes: Make a testobject that counts from 0 to 100 and let it say the numbers to local chat. You will see that in chat the numbers may mixed up. I saw it a lot. If it counts correct on your working sim, go to a busy sim an retry.

I strongly suggest not to use possibility 1, because it will fail sometimes and searching the "error" would be very mean.

**Comment by HowardBaxton** [comment]
I put together a demo which rezzed 20 of the 'Basic Chairs' alternating from normal and explicit.  Tested and tested here with not one issue.  Took the demo to a laggy sim with tons of things happening and tested and tested with not one issue.  Well except when I'd click the die button for explicit props too soon, some would not have their head on yet and would take another click to get them all to die.

This method works.

This method has a bit more code between rezzes than the chat example you want to try.  I think if you were to add a bit more delay as nPose has between chat lines, the count would not be mixed (far far less mix-ups at least).

**Comment by HowardBaxton** [comment]
Works perfectly with nPose-V2 chatchannel mod.
