### ISSUE TITLE
Option to disallow swapping sitting locations

### ISSUE THREAD

**Issue by shadyfox** [HowardBaxton/nPose#71]
An option that will allow a SET that has more than one position to have it only allow a user to change to an unoccupied location. Once you pick a spot, no one can swap you out of it.
i.e. I have a 10 'seat' bench that's a single prim. I might want it so people can't move other people around on the bench by moving to their position and swapping with them. That could be rude. :D

**Comment by LeonaMorro** [comment]
added in nPose 3.0
