### ISSUE TITLE
Layered Animations

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#77]
It would be very nice if we could make a wiki page for layered animations (I currently have no clue how it should work ;) )
I guess with the Bento stuff layered animations will be used much more then today.

**Comment by HowardBaxton** [comment]
Quick explanation:  Multiple animations can be running on the same Avatar.  For example having one sit pose with several layering options to cross legs, legs extended, legs bent straight down, etc. Layering animations was a suggestion by an Animator but it was something that never took off. Using this function requires the builder to explicitly control when an animation should be stopped.  It is a bit difficult to use.  Layering bypasses the nPose core processes and goes straight to the slave script via LINKMSG or SATMSG/NOTSATMSG.

**Comment by LeonaMorro** [comment]
Yes .. I know how the animations will work from the view of the Animations Creator and that sevaral Animations could be played on the same Avatar that are targeting different (or even the same) bones. What I don't know is how to tell nPose to play a bunch of Animations the at the same time.

As I said: I'm quite sure that if the Bento skeleton is released, we will see a lot of Animations that targets only the Face or Hands (everything we currently use the expressions for) so we have to layer them on top of the Animations we are currently using. So I currently looking around for doing so.

Is there a extra skript for the layering animaations? If yes: What is the skriptname (or where can I get it)?

**Comment by LeonaMorro** [comment]
Hi Howard,
thank you very much for the demo. So it is build in and also easy to use.

Some Problems:
1) Sometimes the Avatar is "jumping" .. I don't know how to describe it proper. It seams that all animations are stopped for a small amount of time if I press the "Sip-it" Button.
(I saw this behaviour some times before so I'm not sure if it is related to the layered stuff or if it is a more generell problem.)

2) The Code itself is .. well, id didn't dig much but it starts with:

```
nPose Slave:
        if(num == LAYER_POSE) {
            key av;
            list tempList = llParseString2List(str, ["/"], []);
            if(llListFindList(SeatedAvs(), [(key)llList2String(tempList, 0)]) != -1) {
                av = (key)llList2String(tempList, 0);
            }
            if(av) {
                llRequestPermissions(av, PERMISSION_TRIGGER_ANIMATION);
                av = llGetPermissionsKey();
```

In the last 2 lines Permissions are requested and the script don't really wait for the the permissions to be granted. (Nevertheless the run_time_permissions event will be called and doing all the stuff that a normal animation change would also do)

3) the command syntax:
In (all?) other commands we use the seatnumber/seatname to specify the target. Here we are using the Avatar key. (This may be good in some cases)

**Comment by HowardBaxton** [comment]
It would also be safe to say this script is not optimized for layering animations.  Some re-organizing of the script path may help. Layering routine should probably pass start and stop the layered poses on to the run_time event rather than executing them and then also executing the run_time event functions.

Animation Jumping:
I also see this jumping upon changing a pose mostly.  I see this happening the first time Sip it is run but not on the second time, or third.
In your demo it seems to be happening more often.  My first thought was at a rate with facials and I see some changes needed in the timer to improve performance but find that this is not the cause.
Second thought was maybe AO animation priority but turning off my AO did not change the jumping issue.
Third thought is the quality of animation used.  I do not see this with fixed poses, I have looked at a few more animated poses and do not see this jumping.  This is a possible cause.

More testing to find clues to this jumping issue is needed.

**Comment by LeonaMorro** [comment]
Animation Jumping:
thank for telling me your thoughts:
Maybe your third thought is a hot Candidate for causing the problem:
The Animations I used are:
- static poses (only 1 frame)
- all bones are targeted
- all bones priority 4
  and (I guess the fact that maybe problematic):
- have a ease in and ease out of 0.5s

In the demo I switched the 2 poses with 0.4s (if I remember right). With higher timer values than 0.5s the problem seems to vanish.

But even if the ease in (or ease out) has something to do with the problem I don't know if it really causes the problem. Currently I would say it should work even with the 0.4s timer and so I would call it a bug , .. a bug in nPose ... or in SL ... or in my brain ;)
BTW.: can we (you ;) ) reproduce it in OSGrid too? .. I could give you the used *.anim files

Animation Jumping Layered Animtion (sip):
I saw the problem not only on the first "sip", but also later (sporadic). I don't know if any of the used animations have an ease-in/ease-out .. I guess you don't know it too?

**Comment by HowardBaxton** [comment]
I do not know about the lead in.  It may be just as easy for you to set up
an account in DigiWorldz and upload the anim there.  All uploads are free,
including mesh.  I have the same name there as in SL.  I suspect the
performance to be the same in OSGrids.  Alternately you could also email me
the anime and I can upload them.  Howardbaxton@gmail

**Comment by LeonaMorro** [comment]
I guess I found the bug for the (non-layered) jumping issue .. it is in my brain ;)
I try to explain it in an image:
http://i.imgur.com/HPIHNgP.png
I guess the layered jumping issue is something simillar, but That have to be examined.

**Comment by LeonaMorro** [comment]
I close this issue because the Jumping issue is solved. Maybe I reopen a new issue for the layering of animations. I think we have to implement a nice way to play two or more animations simultaneously. Especially with the upcomming bento stuff which (I guess) will replace the old facials stuff.
