### ISSUE TITLE
SCHMO and SATMSG/NOTSATMSG

### ISSUE THREAD

**Issue by HowardBaxton** [HowardBaxton/nPose#80]
When grouping several SCHMO seats into one notecard with SATMSG lines for each, any time one seat hits the SCHMO card, SATMSG lines for every seat are added to the slots list when only one SCHMO line should get the SATMSG line.  (same for NOTSATMSG lines)

A work around for this is to only have one SCHMO seat and SATMSG and/or NOTSATMSG pair(s) per notecard.

I am looking for a fix for this so that multiple SCHMO/SATMSG lines can be added to a notecard and only fire SATMSG lines when they should (for the menu clicker). Hoping for some ideas.

**Comment by LeonaMorro** [comment]
IMHO:
All is working as expected.
- SCHMO works conditionally
- (NOT)SATMSG works unconditionally

Your idea seems to be making (NOT)SATMSG conditionally too.
You made an example were it would be usefull to change the current behaviour of the (NOT)SATMSG, but I'm sure that I would be able to make an example were changing the behaviour of the both messages would be a bad idea.
We simply don't know what the user has in his mind while writing an NC, so we can't create a ruleset like: "In this case the SATMSG line should be respected and in that case it shouldn't be."

So the only way to "fix" this issue would be: Give the user the possiblity to decide if the (NOT)SATMSG should be executed.
For doing so, I see 2 different possibilities:
1) adding a new command (SATMSG_CONDITIONAL or whatever the name should be)
2) adding some nice things like:

```
IF|CONDITION
    SATMSG...
    whatever....
ENDIF
```
